export const CREATE_ALERT = 'CREATE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOADED = 'LOADED';
export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_CREATED = 'PROFILE_CREATED';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const STICKY_CREATED = 'STICKY_CREATED';
export const STICKY_UPDATED = 'STICKY_UPDATED';